Turbomodule  + Bridgeless support
hyochan/react-native-nitro-sound pull request #602
Opened 2024-04-19 12:02 UTC by sektr63a

This PR converts Native module to Turbomodule
Also updates Example project.

2024-04-19 13:36 UTC, Yasha33 approved these changes
Looks good!

2024-06-09 01:18 UTC, hyochan commented
Wow this is huge 😅 Let me come back soon to review this.

2024-06-11 15:52 UTC, hyochan requested changes
<img width="800" alt="Screenshot 2024-06-12 at 12 49 12 AM" src="https://github.com/hyochan/react-native-audio-recorder-player/assets/27461460/7fa8cf7f-afad-4510-b091-c30a33b77679">

@sektr63a I am having issue testing this `PR`. I've posted the detailed error logs below. Could you kindly guide me how to test your `PR`? I hope I can ship your hard work 🙏

Also would it be possible to upgrade the `example` project to react-native `0.74.2` and not `rc` version?

Thank you so much again for your effort!

### Error Logs
```
Auto-linking React Native modules for target `rnaudiorecorderplayer`: RNAudioRecorderPlayer and rn-fetch-blob
Framework build type is static library
[Codegen] Adding script_phases to React-Codegen.
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json

[!] Invalid `Podfile` file: [!] /Users/hyo/.nvm/versions/node/v20.13.1/bin/node ./../node_modules/react-native/scripts/generate-codegen-artifacts.js -p /Users/hyo/Github/hyochan/react-native-audio-recorder-player/Example/ios/.. -o /Users/hyo/Github/hyochan/react-native-audio-recorder-player/Example/ios -t ios

[Codegen] Analyzing /Users/hyo/Github/hyochan/react-native-audio-recorder-player/Example/package.json
[Codegen] Searching for codegen-enabled libraries in the app.
[Codegen] The "codegenConfig" field is not defined in package.json. Assuming there is nothing to generate at the app level.
[Codegen] Searching for codegen-enabled libraries in the project dependencies.
[Codegen] Found react-native
[Codegen] Found react-native-audio-recorder-player


[Codegen] >>>>> Searching for codegen-enabled libraries in react-native.config.js
[Codegen] Processing FBReactNativeSpec
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Processing rncore
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Processing RNAudioRecorderPlayerSpec
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios for RNAudioRecorderPlayerSpec
[Codegen] Done.
UnsupportedGenericParserError: Module NativeAudioRecorderPlayer: Unrecognized generic type 'AudioSet' in NativeModule spec.
    at translateTypeReferenceAnnotation (/Users/hyo/Github/hyochan/react-native-audio-recorder-player/Example/node_modules/@react-native/codegen/lib/parsers/typescript/modules/index.js:148:15)
    at translateTypeAnnotation (/Users/hyo/Github/hyochan/react-native-audio-recorder-player/Example/node_modules/@react-native/codegen/lib/parsers/typescript/modules/index.js:222:14)
    at /Users/hyo/Github/hyochan/react-native-audio-recorder-player/Example/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:373:11
    at guard (/Users/hyo/Github/hyochan/react-native-audio-recorder-player/Example/node_modules/@react-native/codegen/lib/parsers/utils.js:26:14)
    at translateFunctionTypeAnnotation (/Users/hyo/Github/hyochan/react-native-audio-recorder-player/Example/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:367:25)
    at buildPropertySchema (/Users/hyo/Github/hyochan/react-native-audio-recorder-player/Example/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:484:7)
    at /Users/hyo/Github/hyochan/react-native-audio-recorder-player/Example/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:705:24
    at guard (/Users/hyo/Github/hyochan/react-native-audio-recorder-player/Example/node_modules/@react-native/codegen/lib/parsers/utils.js:26:14)
    at /Users/hyo/Github/hyochan/react-native-audio-recorder-player/Example/node_modules/@react-native/codegen/lib/parsers/parsers-commons.js:702:14
    at Array.map (<anonymous>) {
  nodes: [
    Node {
      type: 'TSTypeReference',
      start: 426,
      end: 434,
      loc: [SourceLocation],
      typeName: [Node]
    }
  ]
}
.

 #  from /Users/hyo/Github/hyochan/react-native-audio-recorder-player/Example/ios/Podfile:20
 #  -------------------------------------------
 #  
 >    use_react_native!(
 #      :path => config[:reactNativePath],
 #  -------------------------------------------

[!] [Codegen] warn: using experimental new codegen integration
```

### What I did

1. Install with yarn from root of the project.
2. Navigate to `Example` and install packages with yarn.
3. Run `yarn ios` (Also tried `pod update && pod install`).

2024-06-27 10:36 UTC, sektr63a commented
Hello @hyochan 

I've just investigated the issue you faced. The main problem is with the types you added:
The **AudioSet** type contains an enum, which is not supported by codegen.
The same applies to the **Record** type.

2024-08-12 16:16 UTC, hyochan commented
> re is some useful article abo

Thanks for coming back! I've just realized this!
Could you kindly explain how to run this example step by step so that I can test your implementation?

Thank you!

2024-10-31 12:42 UTC, efstathiosntonas commented
hey folks, is there any updates on this PR now that react native 0.76 has landed? Thanks!

2025-06-04 06:36 UTC, efstathiosntonas commented
@hyochan hi, are there any plans for this PR? thanks!

2025-06-13 16:08 UTC, hyochan commented
@efstathiosntonas There seem to be quite a few conflicts here, and I’m not able to resolve or test them at the moment 😓

2025-06-13 16:11 UTC, efstathiosntonas commented
@hyochan thanks for the update. ~Wish i could help 🫤~

2025-06-13 16:13 UTC, efstathiosntonas commented
@hyochan maybe I’ll try to at least resolve the conflicts this weekend and make our lives easier at the final testing

2025-09-17 13:11 UTC, ilkerkesici commented
I think this PR is more important for new arch, we didn't set up the library.

2025-09-17 13:31 UTC, hyochan commented
This `PR` can be closed because we already did trial for this in #678 and now we are sticked to `Nitromodule` which supprots New Arch!

2025-09-17 13:31 UTC, closed without merging